config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  get "my_dashboard", to: "pages#my_dashboard", as: :my_dashboard
  root to: 'flight_tickets#index'
  resources :flight_tickets, only:[:index, :show, :new, :create, :edit, :update] do
    resources :purchases, only: [ :create, :new ]
  end
  resources :purchases , only: [:show]
  get "status/:id", to: "flight_tickets#status", as: :status
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/flight_ticket.rb
class FlightTicket < ApplicationRecord
  belongs_to :user
  belongs_to :departure, class_name: 'Airport'
  belongs_to :arrival, class_name: 'Airport'
  has_many :purchase
  validates :airline_code, presence: true
  validates :ticket_number, presence: true, numericality: { only_integer: true }, length: { is: 13 }
  #validates :price, numericality: { only_integer: true }
  validates :departure_at, presence: true
  validate :fields_a_and_b_are_different
  validates :flight_number, format: { with: /\A[a-zA-z]{2}[\d]{3,4}\z/, message: "please enter flight in correct format: 2 letters and 3-4digits"}

  def fields_a_and_b_are_different
    if self.departure_id == self.arrival_id
      errors.add(:arrival_id, 'arrival and departure must be different')
      errors.add(:departure_id, 'arrival and departure must be different')
      #errors.add(:arrival_id, 'must be different to departure')
    end
  end
  include PgSearch::Model
  pg_search_scope :search_by_city,
    against: [ :departure_id, :arrival_id ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/flight_tickets_controller.rb
class FlightTicketsController < ApplicationController
  before_action :set_ticket, only: %i[show edit update status]

  def index
    if params[:departure].present? && params[:arrival].present? && params[:departure_at].present? && params[:arrival_at].present?
      @departure = Airport.find_by_city(params[:departure].capitalize)
      @arrival = Airport.find_by_city(params[:arrival].capitalize)
      @departure_at = DateTime.parse(params[:departure_at])..DateTime.parse(params[:departure_at]) + 24.hour
      @arrival_at = DateTime.parse(params[:arrival_at])..DateTime.parse(params[:arrival_at]) + 24.hour
      @flight_tickets = FlightTicket.where(departure: @departure, arrival: @arrival, departure_at: @departure_at, arrival_at: @arrival_at)
    elsif params[:departure].present? && params[:arrival].present?
      @departure = Airport.find_by_city(params[:departure].capitalize)
      @arrival = Airport.find_by_city(params[:arrival].capitalize)
      @flight_tickets = FlightTicket.where(departure: @departure, arrival: @arrival)
    elsif params[:departure].present? && params[:departure_at].present?
      @departure = Airport.find_by_city(params[:departure].capitalize)
      @departure_at = DateTime.parse(params[:departure_at])..DateTime.parse(params[:departure_at]) + 24.hour
      @flight_tickets = FlightTicket.where(departure: @departure, departure_at: @departure_at)
    elsif params[:departure].present? && params[:arrival].present? && params[:departure_at].present?
      @departure = Airport.find_by_city(params[:departure].capitalize)
      @arrival = Airport.find_by_city(params[:arrival].capitalize)
      @departure_at = DateTime.parse(params[:departure_at])..DateTime.parse(params[:departure_at]) + 24.hour
      @flight_tickets = FlightTicket.where(departure: @departure, arrival: @arrival, departure_at: @departure_at)
    elsif params[:departure].present?
      @departure = Airport.find_by_city(params[:departure].capitalize)
      @flight_tickets = FlightTicket.where(departure: @departure)
    elsif params[:arrival].present?
      @arrival = Airport.find_by_city(params[:arrival].capitalize)
      @flight_tickets = FlightTicket.where(arrival: @arrival)
    elsif params[:departure_at].present?
      @departure_at = DateTime.parse(params[:departure_at])..DateTime.parse(params[:departure_at]) + 24.hour
      @flight_tickets = FlightTicket.where(departure_at: @departure_at)
    elsif params[:arrival_at].present?
      @arrival_at = DateTime.parse(params[:arrival_at])..DateTime.parse(params[:arrival_at]) + 24.hour
      @flight_tickets = FlightTicket.where(arrival_at: @arrival_at)
    else
      @flight_tickets = FlightTicket.all
    end
  end

  def show
    @user = current_user
  end

  def new
    @flight_ticket = FlightTicket.new
    @airports = Airport.order(:city)
  end

  def create
    @flight_ticket = FlightTicket.new(ticket_params)
    @flight_ticket.user_id = current_user.id
    if @flight_ticket.save
      redirect_to edit_flight_ticket_path(@flight_ticket)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flight_ticket.update(ticket_params)
    redirect_to flight_ticket_path(@flight_ticket)
  end

  def status
    @user = current_user
    @flight_ticket = FlightTicket.find(params[:id])
    @arrival = @flight_ticket.arrival
  end

  private
  def ticket_params
    params.require(:flight_ticket).permit(:confirmation_id, :ticket_number, :airline_code, :confirmation_code, :flight_number, :price, :departure_id, :arrival_id, :departure_at, :arrival_at, :user_id)
  end

  def set_ticket
    @flight_ticket = FlightTicket.find(params[:id])
  end
end

app/views/flight_tickets/_signup_popup.html.erb
<div class="box-popup" id="user-validation" style="display: none"; >
    <div class="box">
        <h3>Please sign up or log in</h3>
        <p>In order to book this ticket you need to be logged in</p>
        <div class="formButton" id="validate-btn"><%= link_to "sign up", new_user_registration_path(from_popup:true) %></div>
        <div class="formButton" id="validate-btn"><%= link_to "log in", new_user_session_path(from_popup:true) %></div>
    </div>
</div>

app/views/flight_tickets/_validate.html.erb
<div class="box-popup">
    <div class="box">
        <h3>Congratulations</h3>
        <p>you can swap this ticket!</p>
        <p>you are few clicks away...we need just to know a bit more about you!</p>
        <div class="formButton" id="validate-btn"><%= link_to "Log in", new_user_session_path %></div>
        <div class="formButton" id="validate-btn"><%= link_to "Sign up", new_user_registration_path %></div>
    </div>
</div>

app/views/flight_tickets/edit.html.erb
<div class="container_edit">
  <div class="banner banner_edit">
    <div class="row">
      <p>Departure <%= @flight_ticket.departure.code %></p>
    </div>
    <div class="row">
      <p>Arrival <%= @flight_ticket.arrival.code %></p>
    </div>
  </div>
</div>
<div class="price_tables">
<div class="price_sug">
<!-- Standard Headings -->
<h1 class="price_h1">Price Suggestion Algorithm</h1>

<table class="u-full-width">
  <thead class="t_head">
    <tr>
    <th></th>
      <th>Supplier Name</th>
      <th>Departure Date</th>
      <th>Market Price (€)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <%= simple_form_for @flight_ticket do |f| %>
        <td><%= f.radio_button :price, price = rand(250..500), id: "kiwi-radio" %></td>
        <td>Kiwi</td>
        <td><%= @flight_ticket.departure_at %></td>
        <td id="kiwi-price"><%= price %></td>
      <% end %>
    </tr>
    <tr>
      <%= simple_form_for @flight_ticket do |f| %>
        <td><%= f.radio_button :price, price = rand(250..500), id: "skyscanner-radio" %></td>
        <td>SkyScanner</td>
        <td><%= @flight_ticket.departure_at %></td>
        <td id="skyscanner-price"><%= price %></td>
      <% end %>
    <tr>
      <%= simple_form_for @flight_ticket do |f| %>
        <td><%= f.radio_button :price, price = rand(250..500), id: "kayak-radio" %></td>
        <td>Kayak</td>
        <td><%= @flight_ticket.departure_at %></td>
        <td id="kayak-price"><%= price %></td>
      <% end %>
    </tr>
  </tbody>
</table>
</div>
<div class="price_mine">
<!-- Standard Headings -->
<h1 class="price_h1">Select My Own Price</h1>

<table class="u-full-width mine_table">
  <thead class="t_head">
    <tr>
      <th>Departue Date & Time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @flight_ticket.departure_at %></td>
    </tr>
    <tr>
      <td rowspan="3"><label for="exampleMessage">Please accept SwapTrip's T&C</label>
      <input type="checkbox" value="submit input"></td>
    </tr>
  </tbody>
</table>

<!-- Standard buttons -->



<!-- Primary buttons -->
<%= simple_form_for(@flight_ticket) do |f| %>
 <%= f.input :price, input_html: {id: "price-input" } %>
  <%#input class="button-primary" id="price-verification" type="submit" value="List your offer"%>
  <%= f.submit %>
<% end %>
</div>
</div>
<!-- Note: columns can be nested, but it's not recommended since Skeleton's grid has %-based gutters, meaning a nested grid results in variable with gutters (which can end up being *really* small on certain browser/device sizes) -->

app/views/flight_tickets/index.html.erb
<div class="banner">
  <h1 style="text-align: center; margin-top: 35px; font-size: 40px;">Sell and buy flight tickets with SwapTrip!</h1>
  <div class="wrapper bg-white">
    <%= form_tag flight_tickets_path, method: :get do %>
      <div class="form-group d-sm-flex margin">
        <div class="search_label d-flex align-items-center flex-fill me-sm-1 my-sm-0 my-4 position-relative"> <%= image_tag('departure.svg', :class => "deparr")%>
          <%= text_field_tag :departure,
            params[:departure],
            class: "label_inside form-control",
            placeholder: "City from"
         %>
      </div>
      <%= image_tag('swap_arrows.png', :class => "swap_image")%>
        <div class="search_label d-flex align-items-center flex-fill ms-sm-1 my-sm-0 my-4 position-relative">  <%= image_tag('arrival.svg', :class => "deparr")%>
          <%= text_field_tag :arrival,
            params[:arrival],
            class: "label_inside form-control",
            placeholder: "City to"
          %>
        </div>
      </div>
    <div class="form-group d-sm-flex margin">
      <div class="search_label d-flex align-items-center flex-fill me-sm1 my-sm-0 position-relative">
        <%= date_field_tag :departure_at,
          params[:departure_at],
          class: "label_inside form-control",
          placeholder: "From"
        %>
      </div>
    <div class="search_label search_margin d-flex align-items-center flex-fill ms-sm-1 my-sm-0 my-4 position-relative">
        <%= date_field_tag :arrival_at,
          params[:arrival_at],
          class: "label_inside form-control",
          placeholder: "Return date"
        %>
    </div>

  </div>
    <div class="search_row form-group my-3">
      <%= submit_tag "Search", class: "searchbtn btn btn-primary rounded-0 d-flex justify-content-center text-center p-3" %>
    </div>
    <% end %>
  </div>
</div>
<div class="container">
  <% if params[:departure].present? %>
  <h1 class="all-offers">Flights from <%= params[:departure] %> </h1>
  <% else %>
  <h1 class="all-offers">Latest flight offers </h1>
  <% end %>
</div>
<div class="container-list">
  <div class="cards">
    <% @flight_tickets.each do |flight| %>

      <% unless current_user %>
        <%= render partial: "signup_popup" %>
        <div class="card">
          <div class="cardfirst">
            <% arrival = Airport.find(flight.arrival_id)%>
            <%#= image_tag(arrival.photo, class: "avatar")%>
            <span class="card_first_title"> Price </span>
            <span class="card_first_desc"> <%= flight.price %> €</span>
            <span class="card_first_title"> Dates </span>
            <span class="card_first_desc"> <%= flight.departure_at.strftime("%d/%m") %> - <%= flight.arrival_at.strftime("%d/%m") %></span>
          </div>
          <div class="cardsecond">
            <p class="card_desc"><%= "Flight from #{flight.departure.city} to #{flight.arrival.city}" %></p>
            <div class="card_go">
              <span class="card_second_hours"><%= flight.departure_at.strftime("%I:%M%p") %> </span><%= image_tag('departure.svg', :class => "deparr")%> <span class="card_second_hours"><%= flight.arrival_at.strftime(" %I:%M%p") %> </span><br>
              <span class="air_departure"><%= flight.departure.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= flight.arrival.city %></span>
            </div>
            <div class="card_back">
              <span class="card_second_hours">17:30 AM </span><%= image_tag('arrival.svg', :class => "deparr")%> <span class="card_second_hours">18:50 PM </span><br>
              <span class="air_departure"><%= flight.arrival.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= flight.departure.city %></span>
            </div>
          </div>
          <div class="cardthird">
            <%= image_tag(arrival.photo, class: "card_image")%>
          </div>
        </div>
      <% else %>
      <%= link_to new_flight_ticket_purchase_path(flight) do %>
        <div class="card">
          <div class="cardfirst">
          <% arrival = Airport.find(flight.arrival_id)%>
            <%#= image_tag(arrival.photo, class: "avatar")%>
            <span class="card_first_title"> Price </span>
            <span class="card_first_desc"> <%= flight.price %> €</span>
            <span class="card_first_title"> Dates </span>
            <span class="card_first_desc"> <%= flight.departure_at.strftime("%d/%m") %> - <%= flight.arrival_at.strftime("%d/%m") %></span>
          </div>
          <div class="cardsecond">
            <p class="card_desc"><%= "Flight from #{flight.departure.city} to #{flight.arrival.city}" %></p>
            <div class="card_go">
              <span class="card_second_hours"><%= flight.departure_at.strftime("%I:%M%p") %> </span><%= image_tag('departure.svg', :class => "deparr")%> <span class="card_second_hours"><%= flight.arrival_at.strftime(" %I:%M%p") %> </span><br>
              <span class="air_departure"><%= flight.departure.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= flight.arrival.city %></span>
            </div>
            <div class="card_back">
              <span class="card_second_hours">17:30 AM </span><%= image_tag('arrival.svg', :class => "deparr")%> <span class="card_second_hours">18:50 PM </span><br>
              <span class="air_departure"><%= flight.arrival.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= flight.departure.city %></span>
            </div>
          </div>
          <div class="cardthird">
            <%= image_tag(arrival.photo, class: "card_image")%>
          </div>
        </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="form-container">
    <div class="form-home">
      <div class="form-header">
        <h3 class="form-h3">Check if your flight ticket is swappable!</h3>
        <%= image_tag('ticket.svg', class: "ticket-img-form")%>
        <%= image_tag('airlines.svg', class: "airlines-img-form")%>
      </div>
      <div class="form-fields">
      <p class="form-title">Flight ticket details</p>
        <input type="text" required placeholder="Passanger Full Name" class="label_inside form-control">
        <input type="text" required placeholder="Booking Code" class="label_inside form-control">
        <input type="text" required placeholder="Reservation Email" class="label_inside form-control">
        <input type="text" required placeholder="Flight Number" class="label_inside form-control">
      </div>
      <div class="submit_row form-group my-3">
        <input type ="submit" class="formButton" id="validate-banana" value ="Validate">
      </div>
      </div>
  </div>
</div>
  <div class="validate-bottom">
    <%= render partial: "validate" %>
  </div>

app/views/flight_tickets/new.html.erb
<h1 style="text-align:center">List your flight<h1>
  <div class="container">
    <div class="form-wrapper" style="width: 900px; margin: 0 auto;">
      <%= simple_form_for(@flight_ticket) do |f| %>
        <a title="Thirteen digit code appearing on your flight confirmation email">
        <%= f.input :ticket_number,
          label: "Ticket number",
          placeholder: "E.g. 1258745896524" %>
          </a>
        <a title="Flight number is alphanumerical code consisting of airline code 4 digits">
        <%= f.input :flight_number,
          label: "Flight number",
          placeholder: "E.g. VY850"
          %>
        </a>
        <a title="Alphanumerical code that appears in your flight confirmation">
        <%= f.input :confirmation_code,
          label: "Confirmation code",
          placeholder: "E.g. V3LKZ"%>
        </a>
        <a title="Departure destination of your flight">
        <%= f.association :departure, label_method: :city, collection: Airport.order(:city),
          label: "Departure city",
          placeholder: "Departure"
          %>
        </a>
        <a title="Departure date">
        <%= f.input :departure_at, as: :string, required: false, input_html: {class: "datepicker"},
          label: "Departure date",
          placeholder: "Departure date" %>
        </a>
        <a title="Arrival destination of your flight">
        <%= f.association :arrival, label_method: :city, collection: Airport.order(:city),
          label: "Arrival destination",
          placeholder: "Arrival" %>
        </a>
        <a title="Arrival">
        <%= f.input :arrival_at, as: :string, required: false, input_html: {class: "datepicker"},
           label: "Arrival",
           placeholder: "Arrival date" %>
        </a>
        <a title="Airline code is first two characters from your flight number">
        <%= f.input :airline_code,
           label: "Airline code",
           placeholder: "E.g. VY" %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>

app/views/flight_tickets/show.html.erb
<div class="container">
  <div class="banner-bg">
    <div class="banner">
      <h2 class = "dash-p"> Verification in process!</h2>
      <p>Your flight ticket form has been successfully submitted for a review with SwapTrip</p>
      <p>Thank you for choosing us as your selected service</p>
      <p>Our legal team will review your application and get back to you shortly. In the meantime the status will remain on “pending”.</p>
      <p>As soon you application's status has changed to “approved” you tickets will be listed among other offers. </p>
    </div>
  </div>
    <div class="displaying-card-info">
        <div class ="displaying-card">
            <div class="card">
                <div class="cardfirst">
                <%# <%= image_tag('card_example.svg', class: "avatar")%>
                <span class="card_first_title"> Price </span>
                <span class="card_first_desc"> <%= @flight_ticket.price %>€</span>
                <span class="card_first_title"> Dates </span>
                <span class="card_first_desc"> <%= @flight_ticket.departure_at.strftime("%d/%m") %> - <%= @flight_ticket.arrival_at.strftime("%d/%m") %></span>
                </div>
                <div class="cardsecond">
                <div class="card_go">
                    <span class="card_second_hours"><%= @flight_ticket.departure_at.strftime("%I:%M%p") %> </span><%= image_tag('departure.svg', :class => "deparr")%> <span class="card_second_hours"><%= @flight_ticket.arrival_at.strftime("%I:%M%p") %> </span><br>
                    <span class="air_departure"><%= @flight_ticket.departure.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= @flight_ticket.arrival.city %></span>
                </div>
                <div class="card_back">
                    <span class="card_second_hours"><%= @flight_ticket.arrival_at.strftime("%I:%M%p") %> </span><%= image_tag('arrival.svg', :class => "deparr")%> <span class="card_second_hours"><%= @flight_ticket.departure_at.strftime("%I:%M%p") %> </span><br>
                    <span class="air_departure"><%= @flight_ticket.arrival.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= @flight_ticket.departure.city %></span>
                </div>
                </div>
                <% arrival = Airport.find(@flight_ticket.arrival_id)%>
                <div class="cardthird">
                <%= image_tag(arrival.photo, class: "card_image")%>
                </div>
            </div>
        </div>
        <div class="displaying-info">
            <div class="info-purch-items">
                <i class="fas fa-solid fa-lightbulb"></i>
                <h3>Your application is currently pending a verification from our side. Please come later to check your status.</h3>
            </div>
            <div class="info-purch-items">
                <i class="fas fa-solid fa-eye-slash"></i>
                <div>
                    <h3>The important details of your flight offer remain hidden for other users. As soon as your application is approved, we will show your offer! To check stauts of the submitted flight, please  <%= link_to "click here.", status_path(@flight_ticket) %></h3>
                </div>
            </div>
        </div>
    </div>
</div>







<%# <h1> Verification in process! </h1>


<div class="banner">
  <div class="row">
    <p>Your flight ticket form has been successffuly submitted for a review with SwapFlat.</p>
    <p>Thank you for choosing us as your selected service.</p>
  </div>
  <div class="row">
    <p>Our legal team will review your application and get back to you shortly. In the meantime the status will remain on “pending”.</p>
    <p>As soon you application's status has changed to “approved” you tickets will be listed among other offers. </p>
  </div>
</div>

<div class="card">
  <p>The is where the "empty details" flight card will go</p>
</div>

<div class="row">
  <p>(this goes to the right from the card - For Application Pending) Your application is currently pending a verification from our side. Please come later to check your status. </p>
</div>
<div class="row">
  <a> >Check your status</a>
  <%= link_to "Check your status", status_path(@flight_ticket) %>
<%# </div>


<div class="row">
  <p>(this goes to the right from the card - For Card Hidden) The details of your flight offer remain hidden for now. As soon as your application is approved, we will show your offer! </p>
</div>
<div class="row">
  <a> Take me to my profile</a>
</div> %>

app/views/flight_tickets/status.html.erb
<div class="container">
    <div class="banner-bg">
        <div class="banner">
            <h2 class = "dash-p"> Congratulations!</h2>
            <p>You have officially listed your flight with SwapFlat!</p>
            <p> We would like to thank you for your cooperation and service. Please find below the details of your offer.</p>
        </div>
    </div>
    <div class="displaying-card-info">
        <div class ="displaying-card">
            <div class="card">
                <div class="cardfirst">
                <span class="card_first_title"> Price </span>
                <span class="card_first_desc"> <%= @flight_ticket.price %> €</span>
                <span class="card_first_title"> Dates </span>
                <span class="card_first_desc"> <%= @flight_ticket.departure_at.strftime("%d/%m") %> - <%= @flight_ticket.arrival_at.strftime("%d/%m") %></span>
                </div>
                <div class="cardsecond">
                <div class="card_go">
                    <span class="card_second_hours"><%= @flight_ticket.departure_at.strftime("%I:%M%p") %> </span><%= image_tag('departure.svg', :class => "deparr")%> <span class="card_second_hours"><%= @flight_ticket.arrival_at.strftime(" %I:%M%p") %> </span><br>
                    <span class="air_departure"><%= @flight_ticket.departure.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= @flight_ticket.arrival.city %></span>
                </div>
                <div class="card_back">
                    <span class="card_second_hours">17:30 AM </span><%= image_tag('arrival.svg', :class => "deparr")%> <span class="card_second_hours">18:50 PM </span><br>
                    <span class="air_departure"><%= @flight_ticket.arrival.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= @flight_ticket.departure.city %></span>
                </div>
                </div>
                <div class="cardthird">
                <%= image_tag(@arrival.photo, class: "card_image")%>
                </div>
            </div>
        </div>
        <div class="displaying-info">
            <div class="info-purch-items">
                <i class="fas fa-check-circle"></i>
                <h3>Your offer is now listed to other users. Please naviagate to your user profile to check the status of your offer. </h3>
            </div>
            <div class="info-purch-items">
                <i class="fas fa-ticket-alt"></i>
                <div>
                    <h3>Want to know more information about your ticket? To see all your purchases and offers, please <%= link_to "click here.", my_dashboard_path %></h3>
                </div>
            </div>
        </div>
    </div>
</div>