config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  get "my_dashboard", to: "pages#my_dashboard", as: :my_dashboard
  root to: 'flight_tickets#index'
  resources :flight_tickets, only:[:index, :show, :new, :create, :edit, :update] do
    resources :purchases, only: [ :create, :new ]
  end
  resources :purchases , only: [:show]
  get "status/:id", to: "flight_tickets#status", as: :status
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def show
    @purchase = Purchase.find(params[:id])
    #console
    @flight_ticket = @purchase.flight_ticket
    #@user = current_user
    #@flight_ticket = FlightTicket.find(params[:flight_ticket_id])
     @arrival = @flight_ticket.arrival
  end
  def new
    @purchase = Purchase.new
    @user = current_user
    @flight_ticket = FlightTicket.find(params[:flight_ticket_id])
    @arrival = @flight_ticket.arrival
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @user = current_user
    if @purchase.save!
      redirect_to purchase_path(@purchase)
    else
      render :new
    end
  end

  private

  def purchase_params
    params.permit(:user_id, :flight_ticket_id)
  end
end

app/views/purchases/new.html.erb
<div class="container">
  <div class="buying-process">
    <div class="card-purchase">
        <div class="cardfirst">
          <span class="card_first_title"> Price </span>
          <span class="card_first_desc"> <%= @flight_ticket.price %> €</span>
          <span class="card_first_title"> Dates </span>
          <span class="card_first_desc"> <%= @flight_ticket.departure_at.strftime("%d/%m") %> - <%= @flight_ticket.arrival_at.strftime("%d/%m") %></span>
        </div>
        <div class="cardsecond">
          <div class="card_go">
            <span class="card_second_hours"><%= @flight_ticket.departure_at.strftime("%I:%M%p") %> </span><%= image_tag('departure.svg', :class => "deparr")%> <span class="card_second_hours"><%= @flight_ticket.arrival_at.strftime(" %I:%M%p") %> </span><br>
            <span class="air_departure"><%= @flight_ticket.departure.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= @flight_ticket.arrival.city %></span>
          </div>
          <div class="card_back">
            <span class="card_second_hours">17:30 AM </span><%= image_tag('arrival.svg', :class => "deparr")%> <span class="card_second_hours">18:50 PM </span><br>
            <span class="air_departure"><%= @flight_ticket.arrival.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= @flight_ticket.departure.city %></span>
          </div>
        </div>
        <div class="cardthird">
          <%= image_tag(@arrival.photo, class: "card_image")%>
        </div>
    </div>

    <div class="buy">
      <div class="destinations">
        <h3><strong><%= @flight_ticket.departure.city %></strong> <small>to </small><strong><%= @flight_ticket.arrival.city %></strong></h3>
      </div>

      <div class="flight-price">
        <p><%= @flight_ticket.price %> €</p>
      </div>

      <div>
        <%= link_to "Book Now", flight_ticket_purchases_path(@flight_ticket, user_id: @user), method: "post",  class: "btn btn-warning my-3" %>
        <%# <button type="submit" class="Buy-btn">Buy Now</button> %>
      </div>

    </div>
  </div>
</div>

app/views/purchases/show.html.erb
<div class="container">
    <div class="banner-bg">
        <div class="banner">
            <h2 class = "dash-p">Congratulations!</h2>
            <p>Your reservation has been done successfully!</p>
        </div>
    </div>
    <div class="displaying-card-info">
        <div class ="displaying-card">
            <div class="card">
                <div class="cardfirst">
                <span class="card_first_title"> Price </span>
                <span class="card_first_desc"> <%= @flight_ticket.price %> €</span>
                <span class="card_first_title"> Dates </span>
                <span class="card_first_desc"> <%= @flight_ticket.departure_at.strftime("%d/%m") %> - <%= @flight_ticket.arrival_at.strftime("%d/%m") %></span>
                </div>
                <div class="cardsecond">
                <div class="card_go">
                    <span class="card_second_hours"><%= @flight_ticket.departure_at.strftime("%I:%M%p") %> </span><%= image_tag('departure.svg', :class => "deparr")%> <span class="card_second_hours"><%= @flight_ticket.arrival_at.strftime(" %I:%M%p") %> </span><br>
                    <span class="air_departure"><%= @flight_ticket.departure.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= @flight_ticket.arrival.city %></span>
                </div>
                <div class="card_back">
                    <span class="card_second_hours">17:30 AM </span><%= image_tag('arrival.svg', :class => "deparr")%> <span class="card_second_hours">18:50 PM </span><br>
                    <span class="air_departure"><%= @flight_ticket.arrival.city %> </span><%= image_tag('dots.svg', :class => "deparr")%> <span class="air_departure"><%= @flight_ticket.departure.city %></span>
                </div>
                </div>
                <div class="cardthird">
                <%= image_tag(@arrival.photo, class: "card_image")%>
                </div>
            </div>
        </div>
        <div class="displaying-info">
            <div class="info-purch-items">
                <i class="fas fa-check-circle"></i>
                <h3>Your reservation Has been verified by our legal team. </h3>
            </div>
            <div class="info-purch-items">
                <i class="fas fa-ticket-alt"></i>
                <div class="info-purchase">
                    <h3>Want to know more information about your purchase</h3>
                    <p> All your purchases and offers, <%= link_to "click here", my_dashboard_path %> </p>
                </div>
            </div>
        </div>
    </div>
</div>